# Generated by Django 5.0 on 2023-12-29 17:23

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ChatApps', '0002_chatroom'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='TextMessages',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('message_text', models.CharField(max_length=500)),
                ('send_time', models.DateTimeField(auto_now_add=True)),
                ('send_by', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='user_who_message_send_to_room', to=settings.AUTH_USER_MODEL)),
                ('users_room', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='users_chat_room', to='ChatApps.chatroom')),
            ],
        ),
    ]
