# Generated by Django 5.0 on 2023-12-29 19:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ChatApps', '0003_textmessages'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='textmessages',
            name='send_time',
        ),
        migrations.AddField(
            model_name='textmessages',
            name='send_time_str',
            field=models.CharField(blank=True, max_length=30, null=True),
        ),
    ]
